#!/bin/bash


set -e

print_msg(){
    echo -e "\e[34m$1\e[0m"
}

print_ok(){
    echo -e "\e[32m$1\e[0m"
}

print_err(){
    echo -e "\e[31m$1\e[0m"
    exit
}

check_utils(){
    printf "%s: " $1
    if command -v $1 &> /dev/null
    then
        print_ok "ok\r"
    else
        print_err "no\r"
	print_msg "install wget and 7z and try again"
    fi
}

print_msg "Checking utilities..."

check_utils wget
check_utils 7z

print_msg "Create the /home/autobuild folder..."
sudo mkdir -p /home/autobuild/tools
print_ok "Successfully!"

print_msg "Download the kos32-gcc toolchain..."
wget http://ftp.kolibrios.org/users/Serge/new/Toolchain/x86_64-linux-kos32-5.4.0.7z -O /home/autobuild/tools/kos32-toolchain.7z
print_ok "Successfully!"

print_msg "Extracting files ..."
cd /home/autobuild/tools/
7z x -y kos32-toolchain.7z
rm -rf kos32-toolchain.7z
print_ok "Successfully!"

print_msg "Downloading libraries..."
cd /home/autobuild/tools/win32/mingw32
wget http://ftp.kolibrios.org/users/Serge/new/Toolchain/sdk-28-10-16.7z
7z x -y sdk-28-10-16.7z
rm -rf sdk-28-10-16.7z
print_ok "Successfully!"

libs_dir=http://builds.kolibrios.org/en_US/data/contrib/sdk/lib

print_msg "Updating libraries..."
cd /home/autobuild/tools/win32/mingw32/lib
wget $libs_dir/libdll.a -O libdll.a
wget $libs_dir/libfreetype.a -O libfreetype.a
wget $libs_dir/libc.dll.a -O libc.dll.a
wget $libs_dir/libSDL.a -O libSDL.a
wget $libs_dir/libSDLn.a -O libSDLn.a
wget $libs_dir/libSDL_mixer.a -O libSDL_mixer.a
wget $libs_dir/libz.dll.a -O libz.dll.a


print_msg "Downloading libisl..."
cd /tmp
sudo wget http://board.kolibrios.org/download/file.php?id=8301libisl.so.10.2.2.7z -O /tmp/libisl.so.10.2.2.7z
sudo 7z x -y libisl.so.10.2.2.7z

if ! [ -d /usr/lib/x86_64-linux-gnu/ ]; then
    sudo mkdir -p /usr/lib/x86_64-linux-gnu/
fi

sudo mv /tmp/libisl.so.10.2.2 /usr/lib/x86_64-linux-gnu/libisl.so.10.2.2
sudo ln -sf /usr/lib/x86_64-linux-gnu/libisl.so.10.2.2 /usr/lib/x86_64-linux-gnu/libisl.so.10
sudo ln -sf /usr/lib/x86_64-linux-gnu/libisl.so.10.2.2 /usr/lib/libisl.so.10
sudo chmod go-w /usr/lib/x86_64-linux-gnu/libisl.so.10
sudo chmod go-w /usr/lib/x86_64-linux-gnu/libisl.so.10.2.2
print_ok "Successfully!"

print_msg "Fixing libmpfr..."
sudo ln -sf /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4
sudo ln -sf /usr/lib/libmpfr.so.6 /usr/lib/libmpfr.so.4
print_ok "Successfully!"

#if ! grep -q 'export PATH=$PATH:/home/autobuild/tools/win32/bin' ~/.bashrc; then
#  export PATH=$PATH:/home/autobuild/tools/win32/bin
#  print_msg "Adding '/home/autobuild/tools/win32/bin' to '~/.bashrc'"
#  echo 'export PATH=$PATH:/home/autobuild/tools/win32/bin' >> ~/.bashrc
#
#  export PATH=$PATH:/home/autobuild/tools/win32/bin
#fi

exportpath=home/autobuild/tools/win32/bin

echo 'export PATH=$PATH:$exportpath' >> /etc/environment

export PATH=$PATH:$exportpath

print_ok "Installation was successful!"
